### ISSUE TITLE
進捗の共有

### ISSUE THREAD

**Issue by Niv-Mizzet** [blendtea/EMS#3]
毎日、午後の業務を始める前に自分の進捗をここに書き込みましょう。

**Comment by Niv-Mizzet** [comment]
私は全体の流れを整理するためにメイン画面のアクティビティ図を書いています。

**Comment by blendtea** [comment]
それはいい案ですね。
こちらはログイン認証システムのバグを修正しました。
**問題点** : アカウント作成時に社員IDが重複したまま登録するとエラー画面が流され初めからやり直しになってしまう不具合
**解決** : コントローラー : Accounts.javaのマッピングの修正

### 予定と告知
GitHub [マスターブランチ](https://github.com/blendtea/EMS)の更新 (ビルド1.0.2-experimental)
### 更新後は全員が同じバージョン下で機能追加・修正を行っていただきます。

**Comment by TSawazawa** [comment]
目標：メイン画面の表の機能の実装
機能：「次へ」を押すと次の１０件のデータが表示される
進捗：調べてJSPで書いてみるも、Webページで反映されない

**Comment by blendtea** [comment]
> 目標：メイン画面の表の機能の実装
> 機能：「次へ」を押すと次の１０件のデータが表示される
> 進捗：調べてJSPで書いてみるも、Webページで反映されない

[Thymeleaf](https://www.thymeleaf.org/)でのみ動作します。現状はJSPへの対応はありません。

**Comment by blendtea** [comment]
###   @@在宅の方へ
残念なお知らせですが私が在宅でない限りMySQLサーバーを外部へ公開することが出来ませんので、
もしテストされるようでしたら、本社側に対応してもらってください
また在宅の人ですが、出来ればDiscordの準備をお願いします。

### 開発全員
明日朝から初めにマスターから更新してもらいます。Javaのコーディングをしていた場合は念のため一度ブランチへコミットしてからアップデートをおこなってください。
なお、SQLサーバーは提供できないためGitHubの練習だと思っていただければと思います。

**Comment by Niv-Mizzet** [comment]
進捗報告がdiscoadで行われるようになったのでcloseします
